import { defaultTheme } from "@/components/IFrame";
import { Component } from "@/utils/editor";
import { nanoid } from "nanoid";

export const jsonStructure = (props?: any): Component => {
  const radioGroupId = nanoid();
  const theme = props.theme ?? defaultTheme;

  return {
    id: radioGroupId,
    name: "Radio",
    description: "Radio Complex Group",
    props: {
      name: radioGroupId,
      label: "Select a radio",
      style: {
        width: "auto",
      },
      ...(props.props || {}),
    },
    children: [
      {
        id: nanoid(),
        name: "RadioItem",
        description: "Radio Item",
        props: {
          value: "radio1",
          style: {
            borderRadius: 8,
            borderColor: "rgba(179, 179, 179, 1)",
            borderStyle: "solid",
            borderTopStyle: "solid",
            borderRightStyle: "solid",
            borderBottomStyle: "solid",
            borderLeftStyle: "solid",
            borderWidth: "1px",
            borderTopWidth: "1px",
            borderRightWidth: "1px",
            borderBottomWidth: "1px",
            borderLeftWidth: "1px",
            justifyContent: "center",
            alignItems: "center",
            flexWrap: "wrap",
            display: "flex",
            rowGap: "0px",
            padding: "0px",
            paddingTop: "0px",
            paddingBottom: "0px",
            paddingLeft: "0px",
            paddingRight: "0px",
          },
          bg: "White.0",
          isInsideGroup: true,
          checked: false,
          triggers: {},
        },
        children: [
          {
            id: nanoid(),
            name: "Container",
            description: "Container",
            props: {
              style: {
                display: "flex",
                flexWrap: "wrap",
                flexDirection: "column",
                rowGap: "10px",
                columnGap: "20px",
                alignItems: "center",
                justifyContent: "center",
                position: "relative",
                borderTopStyle: "none",
                borderRightStyle: "none",
                borderBottomStyle: "none",
                borderLeftStyle: "none",
                borderTopWidth: "0px",
                borderRightWidth: "0px",
                borderBottomWidth: "0px",
                borderLeftWidth: "0px",
                borderTopColor: "Border.6",
                borderRightColor: "Border.6",
                borderBottomColor: "Border.6",
                borderLeftColor: "Border.6",
                borderRadius: "0px",
                borderTopLeftRadius: "8px",
                borderTopRightRadius: "8px",
                borderBottomLeftRadius: "8px",
                borderBottomRightRadius: "8px",
                padding: "15px",
                width: "auto",
                height: "auto",
                minHeight: "10px",
                paddingTop: "15px",
                paddingBottom: "15px",
                paddingLeft: "15px",
                paddingRight: "15px",
              },
            },
            children: [
              {
                id: nanoid(),
                name: "Icon",
                description: "Icon",
                children: [],
                props: {
                  name: "IconBox",
                  width: "24px",
                  style: {
                    width: "50px",
                    height: "50px",
                    marginRight: "0px",
                    marginBottom: "0px",
                    color: "rgba(28, 126, 214, 1)",
                    borderTopLeftRadius: "50px",
                    borderTopRightRadius: "50px",
                    borderBottomLeftRadius: "50px",
                    borderBottomRightRadius: "50px",
                    padding: "0px",
                    paddingTop: "0px",
                    paddingBottom: "0px",
                    paddingLeft: "0px",
                    paddingRight: "0px",
                  },
                  bg: "White.6",
                },
                blockDroppingChildrenInside: true,
                states: {
                  hover: {
                    bg: "Border.0",
                  },
                  checked: {
                    bg: "Border.0",
                    style: {
                      borderTopLeftRadius: "70px",
                      borderTopRightRadius: "70px",
                      borderBottomLeftRadius: "70px",
                      borderBottomRightRadius: "70px",
                    },
                  },
                },
              },
              {
                id: nanoid(),
                name: "Icon",
                description: "Icon",
                children: [],
                props: {
                  name: "IconCircleCheck",
                  width: "24px",
                  style: {
                    position: "absolute",
                    top: "5px",
                    right: "5px",
                    width: "26px",
                    height: "26px",
                    color: "rgba(255, 255, 255, 1)",
                    borderTopLeftRadius: "50px",
                    borderTopRightRadius: "50px",
                    borderBottomLeftRadius: "50px",
                    borderBottomRightRadius: "50px",
                  },
                  bg: "White.0",
                },
                blockDroppingChildrenInside: true,
                states: {
                  checked: {
                    style: {
                      color: "rgba(140, 233, 154, 1)",
                    },
                    bg: "Border.1",
                  },
                  hover: {
                    style: {
                      color: "rgba(173, 181, 189, 1)",
                    },
                  },
                },
              },
              {
                id: nanoid(),
                name: "Text",
                description: "Text",
                children: [],
                props: {
                  children: "Expert Appraisal",
                  color: "Black.6",
                  size: "sm",
                  weight: "bold",
                  style: {
                    lineHeight: "110%",
                    letterSpacing: "0px",
                    width: "auto",
                    height: "auto",
                    marginRight: "0px",
                    marginBottom: "0px",
                  },
                },
                blockDroppingChildrenInside: true,
              },
              {
                id: nanoid(),
                name: "Text",
                description: "Text",
                children: [],
                props: {
                  children:
                    "Request an appraisal conducted by a qualified valuer using our technology and productivity tools",
                  color: "Black.4",
                  size: "sm",
                  weight: "normal",
                  style: {
                    lineHeight: "110%",
                    letterSpacing: "0px",
                    width: "205px",
                    height: "auto",
                    marginRight: "0px",
                    marginBottom: "0px",
                  },
                },
                blockDroppingChildrenInside: true,
                states: {
                  checked: {
                    color: "Black.9",
                  },
                },
              },
              {
                id: nanoid(),
                name: "Text",
                description: "Text",
                children: [],
                props: {
                  children: "50 credits per appraisal",
                  color: "Black.6",
                  size: "sm",
                  weight: "bold",
                  style: {
                    lineHeight: "110%",
                    letterSpacing: "0px",
                    width: "auto",
                    height: "auto",
                  },
                },
                blockDroppingChildrenInside: true,
              },
            ],
            states: {
              hover: {
                bg: "Border.7",
              },
              checked: {
                bg: "Success.4",
              },
            },
          },
        ],
        states: {
          hover: {
            bg: "Neutral.6",
          },
        },
      },
      {
        id: nanoid(),
        name: "Text",
        description: "Text",
        children: [],
        props: {
          children: "or",
          color: "Black.6",
          size: "xs",
          weight: "normal",
          style: {
            lineHeight: "110%",
            letterSpacing: "0px",
            width: "auto",
            height: "auto",
          },
        },
        blockDroppingChildrenInside: true,
      },
      {
        id: nanoid(),
        name: "RadioItem",
        description: "Radio Item",
        props: {
          value: "radio3",
          style: {
            borderRadius: 8,
            borderColor: "rgba(179, 179, 179, 1)",
            borderStyle: "solid",
            borderTopStyle: "solid",
            borderRightStyle: "solid",
            borderBottomStyle: "solid",
            borderLeftStyle: "solid",
            borderWidth: "1px",
            borderTopWidth: "1px",
            borderRightWidth: "1px",
            borderBottomWidth: "1px",
            borderLeftWidth: "1px",
            justifyContent: "center",
            alignItems: "center",
            flexWrap: "wrap",
            display: "flex",
          },
          bg: "White.6",
          isInsideGroup: false,
          checked: false,
          triggers: {},
        },
        children: [
          {
            id: nanoid(),
            name: "Container",
            description: "Container",
            props: {
              style: {
                display: "flex",
                flexWrap: "wrap",
                flexDirection: "column",
                rowGap: "10px",
                columnGap: "20px",
                alignItems: "center",
                justifyContent: "center",
                position: "relative",
                borderTopStyle: "none",
                borderRightStyle: "none",
                borderBottomStyle: "none",
                borderLeftStyle: "none",
                borderTopWidth: "0px",
                borderRightWidth: "0px",
                borderBottomWidth: "0px",
                borderLeftWidth: "0px",
                borderTopColor: "Border.6",
                borderRightColor: "Border.6",
                borderBottomColor: "Border.6",
                borderLeftColor: "Border.6",
                borderRadius: "0px",
                borderTopLeftRadius: "8px",
                borderTopRightRadius: "8px",
                borderBottomLeftRadius: "8px",
                borderBottomRightRadius: "8px",
                padding: "15px",
                width: "auto",
                height: "auto",
                minHeight: "10px",
                paddingTop: "15px",
                paddingBottom: "15px",
                paddingLeft: "15px",
                paddingRight: "15px",
              },
            },
            children: [
              {
                id: nanoid(),
                name: "Icon",
                description: "Icon",
                children: [],
                props: {
                  name: "IconCircleCheck",
                  width: "24px",
                  style: {
                    position: "absolute",
                    top: "5px",
                    right: "5px",
                    width: "26px",
                    height: "26px",
                    color: "rgba(255, 255, 255, 1)",
                    borderTopLeftRadius: "50px",
                    borderTopRightRadius: "50px",
                    borderBottomLeftRadius: "50px",
                    borderBottomRightRadius: "50px",
                  },
                  bg: "White.0",
                },
                blockDroppingChildrenInside: true,
                states: {
                  checked: {
                    bg: "White.2",
                    style: {
                      color: "rgba(105, 219, 124, 1)",
                    },
                  },
                  hover: {
                    style: {
                      color: "rgba(173, 181, 189, 1)",
                    },
                  },
                },
              },
              {
                id: nanoid(),
                name: "Icon",
                description: "Icon",
                children: [],
                props: {
                  name: "IconCar",
                  width: "24px",
                  style: {
                    width: "50px",
                    height: "50px",
                    marginRight: "0px",
                    marginBottom: "0px",
                    color: "rgba(28, 126, 214, 1)",
                    borderTopLeftRadius: "50px",
                    borderTopRightRadius: "50px",
                    borderBottomLeftRadius: "50px",
                    borderBottomRightRadius: "50px",
                  },
                  bg: "Border.0",
                },
                blockDroppingChildrenInside: true,
                states: {
                  hover: {
                    bg: "Border.0",
                  },
                },
              },
              {
                id: nanoid(),
                name: "Text",
                description: "Text",
                children: [],
                props: {
                  children: "Expert Appraisal",
                  color: "Black.6",
                  size: "sm",
                  weight: "bold",
                  style: {
                    lineHeight: "110%",
                    letterSpacing: "0px",
                    width: "auto",
                    height: "auto",
                    marginRight: "0px",
                    marginBottom: "0px",
                  },
                },
                blockDroppingChildrenInside: true,
              },
              {
                id: nanoid(),
                name: "Text",
                description: "Text",
                children: [],
                props: {
                  children:
                    "Request an appraisal conducted by a qualified valuer using our technology and productivity tools",
                  color: "Black.4",
                  size: "sm",
                  weight: "normal",
                  style: {
                    lineHeight: "110%",
                    letterSpacing: "0px",
                    width: "205px",
                    height: "auto",
                    marginRight: "0px",
                    marginBottom: "0px",
                  },
                },
                blockDroppingChildrenInside: true,
                states: {
                  checked: {
                    color: "Black.9",
                  },
                },
              },
              {
                id: nanoid(),
                name: "Text",
                description: "Text",
                children: [],
                props: {
                  children: "50 credits per appraisal",
                  color: "Black.6",
                  size: "sm",
                  weight: "bold",
                  style: {
                    lineHeight: "110%",
                    letterSpacing: "0px",
                    width: "auto",
                    height: "auto",
                  },
                },
                blockDroppingChildrenInside: true,
              },
            ],
            states: {
              hover: {
                bg: "Border.7",
              },
              checked: {
                bg: "Success.4",
              },
            },
          },
        ],
        states: {
          hover: {
            bg: "Neutral.6",
          },
        },
      },
      {
        id: nanoid(),
        name: "Text",
        description: "Text",
        children: [],
        props: {
          children: "or",
          color: "Black.6",
          size: "xs",
          weight: "normal",
          style: {
            lineHeight: "110%",
            letterSpacing: "0px",
            width: "auto",
            height: "auto",
          },
        },
        blockDroppingChildrenInside: true,
      },
      {
        id: nanoid(),
        name: "RadioItem",
        description: "Radio Item",
        props: {
          value: "radio2",
          style: {
            borderRadius: 8,
            borderColor: "rgba(179, 179, 179, 1)",
            borderStyle: "solid",
            borderTopStyle: "solid",
            borderRightStyle: "solid",
            borderBottomStyle: "solid",
            borderLeftStyle: "solid",
            borderWidth: "1px",
            borderTopWidth: "1px",
            borderRightWidth: "1px",
            borderBottomWidth: "1px",
            borderLeftWidth: "1px",
            justifyContent: "center",
            alignItems: "center",
            flexWrap: "wrap",
            display: "flex",
          },
          isInsideGroup: true,
          checked: false,
          bg: "White.6",
        },
        children: [
          {
            id: nanoid(),
            name: "Container",
            description: "Container",
            props: {
              style: {
                display: "flex",
                flexWrap: "wrap",
                flexDirection: "column",
                rowGap: "10px",
                columnGap: "20px",
                alignItems: "center",
                justifyContent: "center",
                position: "relative",
                borderTopStyle: "none",
                borderRightStyle: "none",
                borderBottomStyle: "none",
                borderLeftStyle: "none",
                borderTopWidth: "0px",
                borderRightWidth: "0px",
                borderBottomWidth: "0px",
                borderLeftWidth: "0px",
                borderTopColor: "Border.6",
                borderRightColor: "Border.6",
                borderBottomColor: "Border.6",
                borderLeftColor: "Border.6",
                borderRadius: "0px",
                borderTopLeftRadius: "8px",
                borderTopRightRadius: "8px",
                borderBottomLeftRadius: "8px",
                borderBottomRightRadius: "8px",
                padding: "15px",
                width: "auto",
                height: "auto",
                minHeight: "10px",
                paddingTop: "15px",
                paddingBottom: "15px",
                paddingLeft: "15px",
                paddingRight: "15px",
              },
            },
            children: [
              {
                id: nanoid(),
                name: "Icon",
                description: "Icon",
                children: [],
                props: {
                  name: "IconCircleCheck",
                  width: "24px",
                  style: {
                    position: "absolute",
                    top: "5px",
                    right: "5px",
                    width: "26px",
                    height: "26px",
                    color: "rgba(255, 255, 255, 1)",
                    borderTopLeftRadius: "50px",
                    borderTopRightRadius: "50px",
                    borderBottomLeftRadius: "50px",
                    borderBottomRightRadius: "50px",
                  },
                  bg: "White.0",
                },
                blockDroppingChildrenInside: true,
                states: {
                  checked: {
                    bg: "White.0",
                    style: {
                      color: "rgba(105, 219, 124, 1)",
                    },
                  },
                  hover: {
                    style: {
                      color: "rgba(173, 181, 189, 1)",
                    },
                  },
                },
              },
              {
                id: nanoid(),
                name: "Icon",
                description: "Icon",
                children: [],
                props: {
                  name: "IconRobot",
                  width: "24px",
                  style: {
                    width: "50px",
                    height: "50px",
                    marginRight: "0px",
                    marginBottom: "0px",
                    color: "rgba(28, 126, 214, 1)",
                    borderTopLeftRadius: "50px",
                    borderTopRightRadius: "50px",
                    borderBottomLeftRadius: "50px",
                    borderBottomRightRadius: "50px",
                  },
                  bg: "Border.0",
                },
                blockDroppingChildrenInside: true,
                states: {
                  hover: {
                    bg: "Border.0",
                  },
                },
              },
              {
                id: nanoid(),
                name: "Text",
                description: "Text",
                children: [],
                props: {
                  children: "Expert Drive-by Appraisal",
                  color: "Black.6",
                  size: "sm",
                  weight: "bold",
                  style: {
                    lineHeight: "110%",
                    letterSpacing: "0px",
                    width: "auto",
                    height: "auto",
                    marginRight: "0px",
                    marginBottom: "0px",
                  },
                },
                blockDroppingChildrenInside: true,
              },
              {
                id: nanoid(),
                name: "Text",
                description: "Text",
                children: [],
                props: {
                  children:
                    "Request an appraisal conducted by a qualified valuer with an external visit from one of our partners",
                  color: "Black.4",
                  size: "sm",
                  weight: "normal",
                  style: {
                    lineHeight: "110%",
                    letterSpacing: "0px",
                    width: "240px",
                    height: "auto",
                    marginRight: "0px",
                    marginBottom: "0px",
                  },
                },
                blockDroppingChildrenInside: true,
                states: {
                  checked: {
                    color: "Black.9",
                  },
                },
              },
              {
                id: nanoid(),
                name: "Text",
                description: "Text",
                children: [],
                props: {
                  children: "200 credits per appraisal",
                  color: "Black.6",
                  size: "sm",
                  weight: "bold",
                  style: {
                    lineHeight: "110%",
                    letterSpacing: "0px",
                    width: "auto",
                    height: "auto",
                  },
                },
                blockDroppingChildrenInside: true,
              },
            ],
            states: {
              hover: {
                bg: "Border.7",
              },
              checked: {
                bg: "Success.4",
              },
            },
          },
        ],
        states: {
          hover: {
            bg: "Neutral.6",
          },
        },
      },
    ],
  };
};
