import { Component } from "@/utils/editor";
import { nanoid } from "nanoid";

export const jsonStructure = (props?: any): Component => {
  return {
    id: nanoid(),
    name: "RadioItem",
    description: "Radio Item",
    props: {
      value: "radio1",
      ...(props?.props ?? {}),
      style: {
        borderRadius: 8,
        borderColor: "rgba(179, 179, 179, 1)",
        borderStyle: "solid",
        borderTopStyle: "solid",
        borderRightStyle: "solid",
        borderBottomStyle: "solid",
        borderLeftStyle: "solid",
        borderWidth: "1px",
        borderTopWidth: "1px",
        borderRightWidth: "1px",
        borderBottomWidth: "1px",
        borderLeftWidth: "1px",
        justifyContent: "center",
        alignItems: "center",
        flexWrap: "wrap",
        display: "flex",
      },
      bg: "White.6",
      isInsideGroup: false,
      checked: false,
      triggers: {},
    },
    children: [
      {
        id: nanoid(),
        name: "Container",
        description: "Container",
        props: {
          style: {
            display: "flex",
            flexWrap: "wrap",
            flexDirection: "column",
            rowGap: "10px",
            columnGap: "20px",
            alignItems: "center",
            justifyContent: "center",
            position: "relative",
            borderTopStyle: "none",
            borderRightStyle: "none",
            borderBottomStyle: "none",
            borderLeftStyle: "none",
            borderTopWidth: "0px",
            borderRightWidth: "0px",
            borderBottomWidth: "0px",
            borderLeftWidth: "0px",
            borderTopColor: "Border.6",
            borderRightColor: "Border.6",
            borderBottomColor: "Border.6",
            borderLeftColor: "Border.6",
            borderRadius: "0px",
            borderTopLeftRadius: "0px",
            borderTopRightRadius: "0px",
            borderBottomLeftRadius: "0px",
            borderBottomRightRadius: "0px",
            padding: "15px",
            width: "auto",
            height: "auto",
            minHeight: "10px",
            paddingTop: "15px",
            paddingBottom: "15px",
            paddingLeft: "15px",
            paddingRight: "15px",
          },
        },
        children: [
          {
            id: nanoid(),
            name: "Icon",
            description: "Icon",
            children: [],
            props: {
              name: "IconCircleCheck",
              width: "24px",
              style: {
                position: "absolute",
                top: "5px",
                right: "5px",
                width: "26px",
                height: "26px",
                color: "rgba(55, 178, 77, 1)",
              },
            },
            blockDroppingChildrenInside: true,
          },
          {
            id: nanoid(),
            name: "Icon",
            description: "Icon",
            children: [],
            props: {
              name: "IconBox",
              width: "24px",
              style: {
                width: "30px",
                height: "30px",
                marginRight: "0px",
                marginBottom: "0px",
                color: "rgba(28, 126, 214, 1)",
                borderTopLeftRadius: "20px",
                borderTopRightRadius: "20px",
                borderBottomLeftRadius: "20px",
                borderBottomRightRadius: "20px",
              },
              bg: "Border.0",
            },
            blockDroppingChildrenInside: true,
            states: {
              hover: {
                bg: "Border.0",
              },
            },
          },
          {
            id: nanoid(),
            name: "Text",
            description: "Text",
            children: [],
            props: {
              children: "Expert Appraisal",
              color: "Black.6",
              size: "sm",
              weight: "bold",
              style: {
                lineHeight: "110%",
                letterSpacing: "0px",
                width: "auto",
                height: "auto",
                marginRight: "0px",
                marginBottom: "0px",
              },
            },
            blockDroppingChildrenInside: true,
          },
          {
            id: nanoid(),
            name: "Text",
            description: "Text",
            children: [],
            props: {
              children:
                "Request an appraisal conducted by a qualified valuer using our technology and productivity tools",
              color: "Black.4",
              size: "sm",
              weight: "normal",
              style: {
                lineHeight: "110%",
                letterSpacing: "0px",
                width: "205px",
                height: "auto",
                marginRight: "0px",
                marginBottom: "0px",
              },
            },
            blockDroppingChildrenInside: true,
          },
          {
            id: nanoid(),
            name: "Text",
            description: "Text",
            children: [],
            props: {
              children: "50 credits per appraisal",
              color: "Black.6",
              size: "sm",
              weight: "bold",
              style: {
                lineHeight: "110%",
                letterSpacing: "0px",
                width: "auto",
                height: "auto",
              },
            },
            blockDroppingChildrenInside: true,
          },
        ],
        states: {
          hover: {
            bg: "Border.7",
          },
        },
      },
    ],
    states: {
      hover: {
        bg: "Neutral.6",
      },
    },
  };
};
