name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main, develop]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18.x
      SONAR_PROJECT_KEY: dexla-inc_editor-app
      TEST_RESULT_NAME: Editor Front-End Test Results
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Add SonarCloud Scanner
        run: npm install -g sonarqube-scanner

      - name: Begin SonarScanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=dexla-inc \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      - name: End SonarScanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: sonar-scanner \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
